<?php
/**
 * Created by PhpStorm.
 * User: rong
 * Date: 17-11-9
 * Time: 下午5:14
 */
namespace app\admin\controller;

use think\Db;
use think\Request;
class Goods extends Base
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 订单列表
     * @return mixed|string
     */
    public function index()
    {
        $goodlist = Db::name('goods')->order('id','asc')->paginate('15');
        $this->assign('userinfo',$goodlist);
        return $this->fetch();
    }
    /**
     * 语言设置
     */
    public function lang() {
        switch ($_GET['lang']) {
            case 'cn':
                cookie('think_var', 'zh-cn');
                break;
            case 'en':
                cookie('think_var', 'en-us');
                break;
            //其它语言
        }
    }

    /**
     * 搜索
     * @param Request $request
     * @return mixed|string
     */
    public function search(Request $request)
    {
        if($request->isPost()){
            $userId = trim($request->post('user_id'));
            $pageId = trim($request->post('page_id'));
            $goodsNo = trim($request->post('goods_number'));
            $follow = trim($request->post('following'));
            //dump($request->post());
            $where = [];
            if(!empty($userId)){
                $where['user_id'] = ['like',"%$userId%"];
            }
            if(!empty($pageId)){
                $where['page_id'] = ['like',"%$pageId%"];
            }
            if(!empty($goodsNo)){
                $where['goods_number'] = ['like',"%$goodsNo%"];
            }
            if(!empty($follow)){
                $where['following'] = ['like',"%$follow%"];
            }
            $res = Db::name('goods')->where($where)->order('id','asc')->paginate(10);
            $this->assign('userinfo',$res);
            return $this->fetch('index');
        }
    }
}